@auth= eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6OSwiaWF0IjoxNzc3OTQwODk3LCJleHAiOjE3Nzc5Njk2OTd9.gGeB8Fhrqp5Br4EeIwfSuCq-QXDUgd75NDBbONqiLV4

GET http://localhost:3000/api/posts

###

POST http://localhost:3000/api/posts
Content-Type: application/json

{
    "title": "Meu post",
    "content": "conteudo do post",
    "userId": 6
}

###

POST http://localhost:3000/api/posts
Content-Type: application/json
Authorization: Bearer {{auth}}

{
    "title": "titulo",
    "content": "conteudo do post",
    "userId": 9
}

###
POST http://localhost:3000/api/posts
Content-Type: application/json

{
    
}

###

PATCH http://localhost:3000/api/posts/9
Content-Type: application/json

{
    "title": "Meu post modificado",
    "content": "conteudo do post modificado"
}

###
@auth= eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6OSwiaWF0IjoxNzc3OTQwODk3LCJleHAiOjE3Nzc5Njk2OTd9.gGeB8Fhrqp5Br4EeIwfSuCq-QXDUgd75NDBbONqiLV4

PATCH  http://localhost:3000/api/posts/14
Content-Type: application/json
Authorization: Bearer {{auth}}

{
  "title": "teste teste novo teste"
}

###

DELETE http://localhost:3000/api/posts/10

