
GET http://localhost:3000/api/posts

###

POST http://localhost:3000/api/posts
Content-Type: application/json

{
    "title": "Meu post",
    "content": "conteudo do post",
    "userId": 6
}

###

@auth= eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6OSwiaWF0IjoxNzc3NTkxOTcxLCJleHAiOjE3Nzc2MjA3NzF9.2ZKK4pJA2PyQy-ubeRGR3hz4DPNnpj9FZTZGn1sb1k0

POST http://localhost:3000/api/posts
Content-Type: application/json
Authorization: Bearer {{auth}}

{
    "title": "titulo",
    "content": "conteudo do post",
    "userId": 9
}

###
POST http://localhost:3000/api/posts
Content-Type: application/json

{
    
}

###

PATCH http://localhost:3000/api/posts/9
Content-Type: application/json

{
    "title": "Meu post modificado",
    "content": "conteudo do post modificado"
}

###

DELETE http://localhost:3000/api/posts/10

