GET http://localhost:3000/api/users

###

GET http://localhost:3000/api/users/8

###

GET http://localhost:3000/api/users/active

###

POST http://localhost:3000/api/users
Content-Type: application/json

{
    "firstName": "Pessoinha",
    "lastName": "Hey",
    "email": "pessoinha@emailpes.com",
    "phone": "(24)91234-1233",
    "password": "123456"
}

###

POST http://localhost:3000/api/users
Content-Type: application/json

{
    
}

###

DELETE http://localhost:3000/api/users/1

###

PATCH http://localhost:3000/api/users/5
Content-Type: application/json

{
    "firstName": "Maria",
    "lastName": "Gonçalves"
}

###
@authToken = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6OSwicm9sZSI6ImFkbWluIiwiaWF0IjoxNzc4MDIxNDIwLCJleHAiOjE3NzgwNTAyMjB9.3ooX0UZrkudD0QcYuPbzK1tB2yfTm8RI11SvTjRMCwA

PATCH http://localhost:3000/api/users/2/toggle

###

PATCH  http://localhost:3000/api/users
Content-Type: application/json
Authorization: Bearer {{authToken}}

{
  "email": "Hansen de Oliveira 22"
}

###
PATCH  http://localhost:3000/api/users/role/10
Content-Type: application/json
Authorization: Bearer {{authToken}}

{
  "role": "admin"
}



 